// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return kIsWeb
            ? web
            : throw UnsupportedError(
                'Firebase is not natively supported on Linux.',
              );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8EfQzaspJo3jtfoGrZQgJhbvOE2Xe0T4',
    appId: '1:311106651314:web:a9ae7fda37f005cec235ab',
    messagingSenderId: '311106651314',
    projectId: 'animeapp-31e38',
    authDomain: 'animeapp-31e38.firebaseapp.com',
    storageBucket: 'animeapp-31e38.firebasestorage.app',
    measurementId: 'G-1KDKQH70D3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKrHD7Bt-FeT3mIYuxAd76byEOUyU2r_Y',
    appId: '1:311106651314:android:f63b6a213ed45188c235ab',
    messagingSenderId: '311106651314',
    projectId: 'animeapp-31e38',
    storageBucket: 'animeapp-31e38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMkWu0mU6BAxBcZ1bMCo6fyH2hcLCEjM',
    appId: '1:311106651314:ios:5067408c26121423c235ab',
    messagingSenderId: '311106651314',
    projectId: 'animeapp-31e38',
    storageBucket: 'animeapp-31e38.firebasestorage.app',
    androidClientId:
        '311106651314-6bi9d15kgtposfq4nu99n0p75ja2ljga.apps.googleusercontent.com',
    iosClientId:
        '311106651314-invvag8ri31e563a9j106o24teub622i.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMkWu0mU6BAxBcZ1bMCo6fyH2hcLCEjM',
    appId: '1:311106651314:ios:5067408c26121423c235ab',
    messagingSenderId: '311106651314',
    projectId: 'animeapp-31e38',
    storageBucket: 'animeapp-31e38.firebasestorage.app',
    androidClientId:
        '311106651314-6bi9d15kgtposfq4nu99n0p75ja2ljga.apps.googleusercontent.com',
    iosClientId:
        '311106651314-invvag8ri31e563a9j106o24teub622i.apps.googleusercontent.com',
    iosBundleId: 'com.example.animeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8EfQzaspJo3jtfoGrZQgJhbvOE2Xe0T4',
    appId: '1:311106651314:web:6c044da8234a950bc235ab',
    messagingSenderId: '311106651314',
    projectId: 'animeapp-31e38',
    authDomain: 'animeapp-31e38.firebaseapp.com',
    storageBucket: 'animeapp-31e38.firebasestorage.app',
    measurementId: 'G-5RS0X0M83P',
  );
}
